include:
- project: 'quantum-research/tensornetworksimulation/rust-ci'
  ref: 20e5f679ebe1c3623a1419bb21323aec47df92a4
  file: 'template.yml'

variables:
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
